CREATE TABLE [dbo].[SaleOrders] (
    [Id]                     UNIQUEIDENTIFIER   NOT NULL,
    [SalesOrderId]           INT                IDENTITY (1, 1) NOT NULL,
    [RevisionNum]            TINYINT            CONSTRAINT [DF_SalesOrders_RevisionNumber] DEFAULT ((0)) NOT NULL,
    [Date]                   DATETIME           CONSTRAINT [DF_SalesOrders_Date] DEFAULT (getdate()) NOT NULL,
    [DueDate]                DATETIME           NOT NULL,
    [ShipDate]               DATETIME           NULL,
    [Status]                 TINYINT            CONSTRAINT [DF_SalesOrders_Status] DEFAULT ((1)) NOT NULL,
    [IsOnlineOrder]          BIT                CONSTRAINT [DF_SalesOrders_OnlineOrderFlag] DEFAULT ((1)) NOT NULL,
    [Num]                    AS                 (isnull(N'SO'+CONVERT([nvarchar](23),[SalesOrderId],(0)),N'*** ERROR ***')),
    [PurchaseOrderNum]       VARCHAR (25)       NULL,
    [AccountNum]             VARCHAR (15)       NULL,
    [CustomerID]             UNIQUEIDENTIFIER   NOT NULL,
    [ShipToAddressID]        UNIQUEIDENTIFIER   NULL,
    [BillToAddressID]        UNIQUEIDENTIFIER   NULL,
    [ShipMethod]             NVARCHAR (50)      NOT NULL,
    [CreditCardApprovalCode] VARCHAR (15)       NULL,
    [SubTotal]               MONEY              CONSTRAINT [DF_SalesOrders_SubTotal] DEFAULT ((0.00)) NOT NULL,
    [TaxAmt]                 MONEY              CONSTRAINT [DF_SalesOrders_TaxAmt] DEFAULT ((0.00)) NOT NULL,
    [Freight]                MONEY              CONSTRAINT [DF_SalesOrders_Freight] DEFAULT ((0.00)) NOT NULL,
    [TotalDue]               AS                 (isnull(([SubTotal]+[TaxAmt])+[Freight],(0))),
    [Comment]                NVARCHAR (MAX)     NULL,
    [CreatedBy]              VARCHAR (50)       NOT NULL,
    [CreatedOnUtc]           DATETIMEOFFSET (7) NOT NULL,
    [UpdatedBy]              VARCHAR (50)       NULL,
    [UpdatedOnUtc]           DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_SalesOrders] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [CK_SalesOrders_DueDate] CHECK ([DueDate]>=[Date]),
    CONSTRAINT [CK_SalesOrders_Freight] CHECK ([Freight]>=(0.00)),
    CONSTRAINT [CK_SalesOrders_ShipDate] CHECK ([ShipDate]>=[Date] OR [ShipDate] IS NULL),
    CONSTRAINT [CK_SalesOrders_Status] CHECK ([Status]>=(0) AND [Status]<=(8)),
    CONSTRAINT [CK_SalesOrders_SubTotal] CHECK ([SubTotal]>=(0.00)),
    CONSTRAINT [CK_SalesOrders_TaxAmt] CHECK ([TaxAmt]>=(0.00)),
    CONSTRAINT [FK_SalesOrders_Address_BillTo] FOREIGN KEY ([BillToAddressID]) REFERENCES [dbo].[Addresses] ([Id]),
    CONSTRAINT [FK_SalesOrders_Address_ShipTo] FOREIGN KEY ([ShipToAddressID]) REFERENCES [dbo].[Addresses] ([Id]),
    CONSTRAINT [FK_SalesOrders_Customer] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([Id]),
    CONSTRAINT [UIX_SalesOrders] UNIQUE NONCLUSTERED ([Num] ASC)
);

