using System;
using System.ComponentModel.DataAnnotations;

namespace IkeMtz.AdventureWorks.Models
{// Generated by the SQL POCO Class Generator Script
 // Script is available at:
 // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Address :
    IkeMtz.NRSRx.Core.Models.IIdentifiable,
    IkeMtz.NRSRx.Core.Models.IAuditable
  {

    [Required]
    public Guid Id { get; set; }
    [Required]
    [MaxLength(60)]
    public string Line1 { get; set; }
    [MaxLength(60)]
    public string Line2 { get; set; }
    [Required]
    [MaxLength(30)]
    public string City { get; set; }
    [Required]
    [MaxLength(50)]
    public string StateProvince { get; set; }
    [Required]
    [MaxLength(50)]
    public string CountryRegion { get; set; }
    [Required]
    [MaxLength(15)]
    public string PostalCode { get; set; }
    [Required]
    [MaxLength(50)]
    public string CreatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    [MaxLength(50)]
    public string UpdatedBy { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
  }
}
