using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IkeMtz.AdventureWorks.Models
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Client
  : IkeMtz.NRSRx.Core.Models.IIdentifiable, IkeMtz.NRSRx.Core.Models.IAuditable
  {
    public Client()
    {
      ClientAddresses = new HashSet<ClientAddress>();
      SaleOrders = new HashSet<SaleOrder>();
    }

    [Required]
    public Guid Id { get; set; }
    [MaxLength(512)]
    public string Name { get; set; }
    [Required]
    [MaxLength(128)]
    public string CompanyName { get; set; }
    [MaxLength(256)]
    public string SalesPerson { get; set; }
    [MaxLength(50)]
    public string EmailAddress { get; set; }
    [MaxLength(50)]
    public string Phone { get; set; }
    [Required]
    [MaxLength(50)]
    public string CreatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    [MaxLength(50)]
    public string UpdatedBy { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
    public virtual ICollection<ClientAddress> ClientAddresses { get; }
    public virtual ICollection<SaleOrder> SaleOrders { get; }
  }
}
