using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IkeMtz.AdventureWorks.Models
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Customer
  : IkeMtz.NRSRx.Core.Models.IIdentifiable, IkeMtz.NRSRx.Core.Models.IAuditable
  {
    public Customer()
    {
      CustomerAddresses = new HashSet<CustomerAddress>();
      SaleOrders = new HashSet<SaleOrder>();
    }

    [Required]
    public Guid Id { get; set; }
    [Required]
    public bool NameStyle { get; set; }
    [MaxLength(8)]
    public string Title { get; set; }
    [Required]
    [MaxLength(50)]
    public string FirstName { get; set; }
    [MaxLength(50)]
    public string MiddleName { get; set; }
    [Required]
    [MaxLength(50)]
    public string LastName { get; set; }
    [MaxLength(10)]
    public string Suffix { get; set; }
    [MaxLength(128)]
    public string CompanyName { get; set; }
    [MaxLength(256)]
    public string SalesPerson { get; set; }
    [MaxLength(50)]
    public string EmailAddress { get; set; }
    [MaxLength(50)]
    public string Phone { get; set; }
    [Required]
    [MaxLength(50)]
    public string CreatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    [MaxLength(50)]
    public string UpdatedBy { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
    public virtual ICollection<CustomerAddress> CustomerAddresses { get; }
    public virtual ICollection<SaleOrder> SaleOrders { get; }
  }
   

}
