CREATE TABLE [dbo].[SalesAgents](
	[Id] [int] IDENTITY(10000,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[LoginId] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_SalesAgents] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
